name: Course MFE infra CI
on:
  push:
    branches:
      - main
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 

jobs:
  infra-ci:
    runs-on: ubuntu-latest
    name: Provision Infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
      - name: Authenticate with AWS OIDC  
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
      - name: Verify authentication
        run: aws sts get-caller-identity
      - name: Intialize terraform
        working-directory: devops
        run: |
          terraform init -backend-config="variables/dev/dev.backend.tfvars"
      - name: Terraform Plan
        working-directory: devops
        run: |
          terraform plan -var-file="variables/dev/dev.tfvars" -out=tfplan
      - name: Apply terraform plan
        working-directory: devops
        run: |
          terraform show -json tfplan
          terraform apply -auto-approve tfplan
      

